#ifndef ENTITIES_H
#define ENTITIES_H

// Entity IDs extracted from entities.txt
// Format: #define ENTITY_NAME 0xHEX_ID

// FILE 018
#define ENTITY_UNKNOWN_UNUSED_079 0x079
#define ENTITY_UNKNOWN_UNUSED_07C 0x07c
#define ENTITY_UNKNOWN_UNUSED_101 0x101
#define ENTITY_DANGO_STICK_WIPERS 0x134
#define ENTITY_SPINY_SEA_URCHIN_KII_AWAJI 0x13b
#define ENTITY_DANGO_STICK_WIPERS_SPAWNERS 0x149
#define ENTITY_SPIKE_CHAIN 0x198
#define ENTITY_JUMP_ROPE_GHOST_TOYS 0x1aa
#define ENTITY_GLITCHY_SPIKE_CHAIN_SPIKES_UNUSED 0x1ab
#define ENTITY_UNKNOWN_35E 0x35e
#define ENTITY_SPIKE_FLOOR_GHOST_TOYS 0x3ca

// FILE 019
#define ENTITY_UNKNOWN_UNUSED_07D 0x07d
#define ENTITY_THE_WATER_HUSBAND_AND_WIFE_ROCKS 0x249

// FILE 01a
#define ENTITY_RYO 0x082
#define ENTITY_GOLD_DANGO 0x085
#define ENTITY_MR_ELLY_FANT 0x086
#define ENTITY_MR_ARROW 0x087
#define ENTITY_SILVER_DOLL 0x088
#define ENTITY_GOLD_DOLL 0x089
#define ENTITY_SURPRISE_PACK_EXTRA_LIFE 0x091

// FILE 01b
#define ENTITY_SHOP_WARES 0x08a
#define ENTITY_UNKNOWN_UNUSED_2F1 0x2f1
#define ENTITY_UNKNOWN_UNUSED_2F2 0x2f2
#define ENTITY_UNKNOWN_UNUSED_2F3 0x2f3
#define ENTITY_PLASMA_BACKUP_DANCER 0x2f5
#define ENTITY_CHEF_DEALS_CONTACT_DAMAGE 0x2f6
#define ENTITY_WOMAN_AT_TOURISM_CENTER_WITH_RICE_BALL 0x2f7
#define ENTITY_DRUNK 0x2f8
#define ENTITY_SLEEPING_WOMAN 0x2f9
#define ENTITY_KNEELING_WOMAN_UNUSED 0x2fa
#define ENTITY_KNEELING_WOMAN_WITH_FAN_FROM_INN 0x2fb
#define ENTITY_SHOPKEEPER 0x2fc
#define ENTITY_OLD_WOMAN 0x2fd
#define ENTITY_TOUR_GUIDE 0x2fe
#define ENTITY_MAN_IN_BLUE_KIMONO_UNUSED 0x2ff
#define ENTITY_PRIEST 0x300
#define ENTITY_RESTAURANT_HOSTESS 0x301
#define ENTITY_INN_KEEPER 0x302
#define ENTITY_UNKNOWN_UNUSED_303 0x303
#define ENTITY_GUARDHOUSE_GUARD 0x304
#define ENTITY_MOKUBEI_PIPE_MAKER 0x305
#define ENTITY_PLASMA 0x306
#define ENTITY_GYM_TRAINER 0x307
#define ENTITY_FIXED_CAMERA_ACTOR 0x308
#define ENTITY_TOURISM_CENTER_TELEPORT_MACHINE 0x30a
#define ENTITY_UNKNOWN_UNUSED_30C 0x30c
#define ENTITY_UNKNOWN_UNUSED_30D 0x30d
#define ENTITY_UNKNOWN_UNUSED_313 0x313
#define ENTITY_OMITSU 0x31e
#define ENTITY_WITCH 0x346
#define ENTITY_EBOSHI_PRIEST 0x347
#define ENTITY_UNKNOWN_UNUSED_36D 0x36d
#define ENTITY_RESIDENCE_TROUGH_CONTENTS 0x3fd
#define ENTITY_RESTAURANT_PATRON_OR_PROP 0x401

// FILE 01c
#define ENTITY_DANGO_08F 0x08f
#define ENTITY_POT 0x192

// FILE 01d
#define ENTITY_UNKNOWN_UNUSED_0C8 0x0c8
#define ENTITY_UNKNOWN_UNUSED_0C9 0x0c9
#define ENTITY_GHOST_ROBOT_TSURAMI 0x0cb
#define ENTITY_UNKNOWN_UNUSED_0CD 0x0cd
#define ENTITY_CONGO_BOSS_EVENT_TRIGGER 0x0ce
#define ENTITY_UNKNOWN_UNUSED_0D0 0x0d0
#define ENTITY_UNKNOWN_UNUSED_2D5 0x2d5
#define ENTITY_OEDO_CASTLE_BARON_EVENT_TRIGGER 0x2d7
#define ENTITY_CONGO 0x323
#define ENTITY_TSURAMI_BOSS_TRIGGER 0x357
#define ENTITY_UNKNOWN_UNUSED_36C 0x36c

// FILE 01e
#define ENTITY_CONGOS_HAND 0x0ca
#define ENTITY_STAR_BLOCK 0x196
#define ENTITY_CRUSHER 0x197
#define ENTITY_SLICER_MUSICAL_CASTLE_1 0x19d
#define ENTITY_CRANE_GAME_CRANE_AND_GLASS 0x1b9
#define ENTITY_CRANE_GAME_POWER_SWITCH 0x1ba
#define ENTITY_CRANE_GAME_CONTROL_PANEL 0x1bb
#define ENTITY_CRANE_GAME_FIXED_POV 0x1bf
#define ENTITY_UNKNOWN_UNUSED_1C1 0x1c1
#define ENTITY_UNKNOWN_UNUSED_1C2 0x1c2
#define ENTITY_TURTLE_PAD 0x1f7
#define ENTITY_SMALL_WOODEN_BOX_CARRYABLE_UNUSED 0x243
#define ENTITY_LARGE_WOODEN_BOX_PUSHABLE_UNUSED 0x244
#define ENTITY_METAL_BOX 0x245
#define ENTITY_LADDER_322 0x322
#define ENTITY_EXPANDING_STAIRCASE_BLOCK 0x324
#define ENTITY_RETRACTABLE_PLATFORM 0x326
#define ENTITY_TRANSLUCENT_WALL 0x32a
#define ENTITY_UNKNOWN_UNUSED_32B 0x32b
#define ENTITY_GLOWING_IN_SIGN 0x330
#define ENTITY_GIANT_TURBINE_GOURMET_SUB 0x331
#define ENTITY_TREADMILL_GOURMET_SUB 0x332
#define ENTITY_UNKNOWN_UNUSED_337 0x337
#define ENTITY_ENTERABLE_SUBMARINE 0x339
#define ENTITY_LADDER_33B 0x33b
#define ENTITY_LADDER_33C 0x33c
#define ENTITY_ROTATING_COLUMN_ELEVATOR 0x34a
#define ENTITY_SLIDING_DOOR_PINK_ROBOT_SPAWNER 0x354
#define ENTITY_GIANT_KALEIDOSCOPE 0x356
#define ENTITY_MIRACLE_MOON 0x35f
#define ENTITY_FAST_BOAT_GHOST_TOYS 0x3b4
#define ENTITY_BLOOMING_FLOWER_GHOST_TOYS 0x3d0
#define ENTITY_MEATSAW_HAMMER 0x3d2
#define ENTITY_WIND_UP_CAMERA 0x3d3
#define ENTITY_ICE_KUNAI 0x3d4
#define ENTITY_YAE_BAZOOKA 0x3d5
#define ENTITY_UNKNOWN_3EC_GOURMET_SUB 0x3ec
#define ENTITY_SPINY_URCHIN_SPAWNER_GOURMET_SUB 0x3ef

// FILE 01f
#define ENTITY_DARUMANYO_BOSS_EVENT_TRIGGER_1 0x0cc
#define ENTITY_DARUMANYO_BOSS_EVENT_TRIGGER_2 0x0cf

// FILE 020
#define ENTITY_ROBOT_BEE 0x0fa
#define ENTITY_PINK_ROBOT_FB 0x0fb
#define ENTITY_PINK_ROBOT_FC 0x0fc
#define ENTITY_GREEN_ROBOT_FD 0x0fd
#define ENTITY_GREEN_ROBOT_FE 0x0fe
#define ENTITY_BLUE_ROBOT 0x100
#define ENTITY_SCARECROW_BOT 0x103
#define ENTITY_PINK_ROBOT_110_FESTIVAL_TEMPLE_AND_HAGI 0x110
#define ENTITY_SMALL_CANNON 0x12c
#define ENTITY_FLYING_DRAGON_HEAD 0x12d
#define ENTITY_DRUM_ROBOT 0x130
#define ENTITY_DRUM_ROBOT_UNUSED 0x146

// FILE 021
#define ENTITY_BIG_SWATTING_ROBOT 0x0ff
#define ENTITY_UNKNOWN_UNUSED_10D 0x10d
#define ENTITY_UNKNOWN_UNUSED_10E 0x10e

// FILE 022
#define ENTITY_SLINKY_ENEMY_MT_FUJI 0x102
#define ENTITY_ROLLING_BOULDER_UNUSED 0x191
#define ENTITY_FALLING_BARREL 0x19a
#define ENTITY_BOULDER_KOMPIRA_MOUNTAIN 0x3da

// FILE 023
#define ENTITY_CAN_CAN_LEGS 0x104
#define ENTITY_SPINNING_KITE 0x106
#define ENTITY_CAN_CAN_LEGS_1X_UNUSED 0x10f
#define ENTITY_BOUNCING_DARUMANYO 0x132
#define ENTITY_PAPER_GHOST 0x133
#define ENTITY_KITE 0x145
#define ENTITY_WATER_SNAKE 0x148
#define ENTITY_FLOATING_INGREDIENTS_GOURMET_SUB 0x3d1

// FILE 024
#define ENTITY_FLATFISH_TOSA_BRIDGE 0x105
#define ENTITY_SWORD_ROBOT 0x10c
#define ENTITY_TRIANGLE_ROBOT 0x131
#define ENTITY_UNKNOWN_UNUSED_138 0x138
#define ENTITY_GIANT_ENEMY_CRAB 0x13c
#define ENTITY_SAMURAI 0x13d
#define ENTITY_HAMMER_THROWER 0x13f
#define ENTITY_BOMBER_BIRD 0x147

// FILE 025
#define ENTITY_BAMBOO_SHOOTER 0x107
#define ENTITY_UNKNOWN_UNUSED_135 0x135
#define ENTITY_RED_EYE_FISH 0x136
#define ENTITY_ROSE_ROBOT 0x13e
#define ENTITY_FIRE_STALKER 0x140
#define ENTITY_NINJA 0x141
#define ENTITY_FLYING_TILE 0x190
#define ENTITY_FOX_MASK 0x1a6
#define ENTITY_UNKNOWN_UNUSED_364 0x364

// FILE 026
#define ENTITY_JET_ROBOT 0x108
#define ENTITY_YELLOW_ROBOT 0x109
#define ENTITY_BIG_SWATTING_ROBOT_RED 0x10a
#define ENTITY_SHRINKING_ROBOT 0x10b
#define ENTITY_GREEN_ROBOT_WITH_YELLOW_ROBOT_BLASTER_BOX_UNUSED 0x362

// FILE 027
#define ENTITY_SEAHORSE 0x12e
#define ENTITY_SPINY_SEA_URCHIN 0x12f
#define ENTITY_BURROWING_ROBOT 0x144
#define ENTITY_UNKNOWN_UNUSED_363 0x363
#define ENTITY_FLOOR_FLAMETHROWER 0x3fc

// FILE 028
#define ENTITY_UNKNOWN_UNUSED_137 0x137
#define ENTITY_UNKNOWN_UNUSED_139 0x139
#define ENTITY_GHOST_TOYS_TORCH 0x195
#define ENTITY_FAN_PLATFORM_SPREADING 0x19e
#define ENTITY_FAN_PLATFORM_ROTATING 0x19f
#define ENTITY_UNKNOWN_UNUSED_1A4 0x1a4
#define ENTITY_UNKNOWN_UNUSED_1A5 0x1a5
#define ENTITY_UNKNOWN_UNUSED_1A8 0x1a8
#define ENTITY_FALLING_BOMB_BLOCK 0x1a9
#define ENTITY_FESTIVAL_TEMPLE_FISH_KITE 0x320
#define ENTITY_UNKNOWN_UNUSED_333 0x333
#define ENTITY_SUSHI_SPAWNER_GOURMET_SUB 0x334
#define ENTITY_GIANT_SPINNING_TOP_GHOST_TOYS 0x365
#define ENTITY_SPINNING_RECTANGULAR_PLATFORM_GHOST_TOYS 0x366
#define ENTITY_FALSE_FLOOR_GHOST_TOYS 0x3c4
#define ENTITY_INVISIBLE_PATH_GOURMET_SUB 0x3c5
#define ENTITY_RAMEN_BOWL_PLATFORM_GOURMET_SUB 0x3c6
#define ENTITY_FESTIVAL_TEMPLE_ACCORDION_STAIRS 0x3cb

// FILE 029
#define ENTITY_TANK 0x13a

// FILE 02a
#define ENTITY_SWEETS_MINIGAME 0x142
#define ENTITY_UNKNOWN_UNUSED_1AC 0x1ac
#define ENTITY_SWEETS_FROM_SWEETS_MINIGAME_UNUSED 0x1ad
#define ENTITY_GIANT_PORTRAIT_CASTING_A_SHADOW_UNUSED 0x1ae
#define ENTITY_HUGE_SHADOW_UNUSED 0x1b1

// FILE 02b
#define ENTITY_KEY 0x193
#define ENTITY_UNKNOWN_UNUSED_194 0x194
#define ENTITY_UNKNOWN_UNUSED_199 0x199
#define ENTITY_UNKNOWN_UNUSED_1A2 0x1a2
#define ENTITY_DOUBLE_SLIDING_DOOR_23A 0x23a
#define ENTITY_DOUBLE_SLIDING_DOOR_23B 0x23b
#define ENTITY_DOUBLE_SLIDING_DOOR_23C 0x23c
#define ENTITY_BOMBABLE_WALL 0x23d
#define ENTITY_LOCKED_DOOR 0x23e
#define ENTITY_SLIDING_DOOR_MUSICAL_CASTLE 0x23f
#define ENTITY_SWING_DOOR 0x241
#define ENTITY_SWING_DOOR_SHORT 0x242
#define ENTITY_SLIDING_DOOR_24D 0x24d
#define ENTITY_SLIDING_DOOR_256 0x256
#define ENTITY_DOUBLE_CROSS_SLIDING_DOOR 0x31f
#define ENTITY_SLIDING_DOOR_GHOST_TOYS 0x321
#define ENTITY_AUTOMATIC_DOOR_GOURMET_SUB 0x32f
#define ENTITY_DOOR_TO_YAMATO_SHRINE 0x340
#define ENTITY_TORII_GATE_TO_HUSBAND_AND_WIFE_ROCKS 0x341
#define ENTITY_TORII_RETURN_GATE_TO_KII_AWAJI_ISLAND 0x342
#define ENTITY_SMALL_BOAT 0x343
#define ENTITY_INVISIBLE_WALL_THAT_BLOCKS_DOORS_UNTIL_EVENT_CONDITIONS_ARE_MET 0x345
#define ENTITY_SOGEN_MAZE_GATE 0x348
#define ENTITY_DOOR_TO_OEDO_LORDS_ROOM 0x34b
#define ENTITY_GHOST_TOYS_ENTRANCE_BARRICADE 0x3c8
#define ENTITY_UNKNOWN_3C9_MUTSU_SHORELINE 0x3c9
#define ENTITY_UNKNOWN_UNUSED_3D7 0x3d7
#define ENTITY_UNKNOWN_UNUSED_3EB 0x3eb

// FILE 02c
#define ENTITY_DRUM_PLATFORM 0x1a1
#define ENTITY_TREADMILL_MUSICAL_CASTLE_2 0x1a3
#define ENTITY_PLATFORM_STATIONARY 0x1f4
#define ENTITY_PLATFORM_STATIONARY_UNUSED 0x1f5
#define ENTITY_UNKNOWN_UNUSED_1F6 0x1f6
#define ENTITY_ELEVATOR 0x1fc
#define ENTITY_SHOGI_PLATFORM 0x1fd
#define ENTITY_HOT_PLATFORM 0x1fe
#define ENTITY_MOVING_PLATFORM_HORIZONTAL 0x228
#define ENTITY_MOVING_PLATFORM_VERTICAL_OR_ROTATING 0x3e0

// FILE 02d
#define ENTITY_UNKNOWN_UNUSED_1AF 0x1af
#define ENTITY_WISEMANS_HOUSE_IMPACT_BOSS_TRIGGER_IGA 0x24c
#define ENTITY_UNKNOWN_UNUSED_30B 0x30b
#define ENTITY_UNKNOWN_UNUSED_317 0x317
#define ENTITY_UNKNOWN_UNUSED_318 0x318

// FILE 02e
#define ENTITY_MIND_CONTROL_ROBOT 0x1b0
#define ENTITY_UNKNOWN_UNUSED_1B4 0x1b4
#define ENTITY_UNKNOWN_UNUSED_1B5 0x1b5
#define ENTITY_ROBOT_BEE_SPAWNER 0x1b6
#define ENTITY_BILLIARD_BALLS_ALL_OF_THEM 0x1bd
#define ENTITY_BILLIARD_BALL_UNUSED 0x1be
#define ENTITY_UNKNOWN_UNUSED_3DB 0x3db

// FILE 02f
#define ENTITY_HIGH_JUMP_MINIGAME 0x1b2

// FILE 030
#define ENTITY_SUDDEN_IMPACT_MINIGAME 0x1bc

// FILE 031
#define ENTITY_BENKEI 0x1c0
#define ENTITY_UNKNOWN_UNUSED_1C3 0x1c3

// FILE 032
#define ENTITY_SWITCH 0x226
#define ENTITY_UNKNOWN_UNUSED_227 0x227

// FILE 033
#define ENTITY_DOOR_TO_MUSASHI 0x240
#define ENTITY_GUARD_GATEKEEPER 0x2d0
#define ENTITY_MUSASHI_BRIDGE_INVISIBLE_WALL 0x311

// FILE 034
#define ENTITY_UNKNOWN_OEDO_CASTLE_ENTRANCE 0x246

// FILE 035
#define ENTITY_UNKNOWN_UNUSED_24E 0x24e
#define ENTITY_KYUSHU_ALL_OF_IT 0x316
#define ENTITY_UNKNOWN_UNUSED_31B 0x31b
#define ENTITY_UNKNOWN_UNUSED_33F 0x33f

// FILE 036
#define ENTITY_LORD_OF_OEDO_CASTLE_EVENT_TRIGGER 0x255
#define ENTITY_LORD_OF_OEDO 0x2d3
#define ENTITY_PRINCESS_YUKI 0x2d4

// FILE 037
#define ENTITY_YAE_INTRODUCTION_EVENT_TRIGGER 0x257

// FILE 038
#define ENTITY_UNKNOWN_UNUSED_27A 0x27a
#define ENTITY_UNKNOWN_UNUSED_27E 0x27e
#define ENTITY_WATER 0x287
#define ENTITY_WATERFALL_MIST 0x288
#define ENTITY_WATERFALL_RIPPLE 0x289
#define ENTITY_UNKNOWN_KAI_HIGHWAY 0x28b
#define ENTITY_FALLING_SNOW_WEATHER_EFFECT 0x28d
#define ENTITY_UNKNOWN_UNUSED_2BC 0x2bc
#define ENTITY_UNKNOWN_RELATED_TO_WATER_IN_GHOST_TOYS 0x3b6
#define ENTITY_SOUND_OF_FLOWING_WATER_IN_STEREO 0x3e1
#define ENTITY_WAVES_FLOORING_MUSICAL_CASTLE_1 0x3f0

// FILE 039
#define ENTITY_USHIKAWA 0x28f
#define ENTITY_UNKNOWN_GOLDEN_TEMPLE 0x290
#define ENTITY_PRIEST_GOLDEN_TEMPLE 0x291
#define ENTITY_FLAME 0x349

// FILE 03a
#define ENTITY_DRAGONBACK_CUTSCENE_TRIGGERS_ALL_OF_THEM 0x2a0

// FILE 03b
#define ENTITY_DOG 0x2bd
#define ENTITY_OLD_MAN 0x2be
#define ENTITY_BOY 0x2bf
#define ENTITY_PURPLE_WOMAN 0x2c0
#define ENTITY_GIRL 0x2c1
#define ENTITY_HAPPY_BROWN_MAN 0x2c2
#define ENTITY_HAPPY_BROWN_MAN_GLITCHY_UNUSED 0x2c3
#define ENTITY_THIEF 0x2c4
#define ENTITY_HIKER 0x2c5
#define ENTITY_MIDDLE_AGED_BROWN_MAN 0x2c6
#define ENTITY_BLUE_MAN 0x2c7
#define ENTITY_RED_WOMAN 0x2c8
#define ENTITY_RUNNING_MAN 0x2c9
#define ENTITY_FARMER 0x2ca
#define ENTITY_RONIN 0x2cb
#define ENTITY_GUARD 0x2cc
#define ENTITY_GATEKEEPER_WITH_LANTERN 0x2cd
#define ENTITY_YOUNG_WOMAN 0x2ce
#define ENTITY_UNKNOWN_UNUSED_2CF 0x2cf
#define ENTITY_BOY_FOLKYPOKE 0x2d8
#define ENTITY_GIRL_FOLKYPOKE 0x2d9
#define ENTITY_HIKER_BOY_BIZEN_BRIDGE 0x32e

// FILE 03c
#define ENTITY_CREDITS_SEQUENCE 0x2dc

// FILE 03d
#define ENTITY_INN_CUTSCENE 0x309
#define ENTITY_UNKNOWN_34E_GOEMONS_HOUSE 0x34e
#define ENTITY_SECRET_DECORATIONS_GOEMONS_HOUSE 0x400

// FILE 03e
#define ENTITY_KAPPA_EVENT_TRIGGER 0x315
#define ENTITY_SHISHI_ODOSHI 0x3d6

// FILE 03f
#define ENTITY_KOMPIRA_SHRINE_COLLECTION_BOX 0x319

// FILE 040
#define ENTITY_GIANT_BOULDER_MT_FEAR 0x325

// FILE 041
#define ENTITY_THE_TURTLE_ROCK 0x329

// FILE 042
#define ENTITY_UNKNOWN_UNUSED_32C 0x32c
#define ENTITY_INABA_BATTERY 0x32d
#define ENTITY_IZUMO_TREE_BATTERY 0x3c7

// FILE 043
#define ENTITY_PEMOPEMO_GOD 0x335
#define ENTITY_UNKNOWN_UNUSED_336 0x336
#define ENTITY_UNKNOWN_UNUSED_33E 0x33e

// FILE 044
#define ENTITY_ZAZEN_FISH 0x338

// FILE 045
#define ENTITY_SIGN_WATERFALL_OF_KEGON 0x33a

// FILE 046
#define ENTITY_UNKNOWN_344_MUTSU_SHORELINE 0x344

// FILE 047
#define ENTITY_UNKNOWN_DARUMANYO_BOSS_ROOM 0x34f

// FILE 048
#define ENTITY_UNKNOWN_KOMPIRA_MOUNTAIN_BASE 0x355

// FILE 049
#define ENTITY_UNKNOWN_TSURAMI_BOSS_ROOM 0x358

// FILE 04a
#define ENTITY_THE_GORGEOUS_STAGE 0x35c

// FILE 04b
#define ENTITY_GORGEOUS_PERFORMANCE_TRIGGER 0x35d

// FILE 04c
#define ENTITY_UNKNOWN_OUTSIDE_OEDO_CASTLE 0x36b

// FILE 04d
#define ENTITY_THAISAMBA_BOSS_TRIGGER 0x3b5

// FILE 04e
#define ENTITY_DIM_LIGHTING_WITCHS_HOUSE 0x3d9

// FILE 04f
#define ENTITY_UNKNOWN_PIPE_MAKERS_HOUSE 0x3dc
#define ENTITY_WISE_OLD_MAN_SOGEN_RESTAURANT 0x3dd

// FILE 050
#define ENTITY_HOT_FLOOR_STEAM_GOURMET_SUB 0x3de
#define ENTITY_HOT_SPRING_STEAM_IYO 0x3ea

#endif // ENTITIES_H